language: php

matrix:
    fast_finish: true
    include:
        - php: 5.6
        - php: 7.0
        - php: hhvm

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

install:
    - composer install

script:
    - vendor/bin/php-cs-fixer --diff --dry-run -v fix src
    - vendor/bin/php-cs-fixer --diff --dry-run -v fix tests
    - vendor/bin/phpunit