language: php

matrix:
    fast_finish: true
    include:
        - php: 5.3
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: 7.0
        - php: hhvm

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

install:
    - travis_retry composer update $COMPOSER_FLAGS --no-interaction

script:
    - vendor/bin/php-cs-fixer --diff --dry-run -v fix src
    - vendor/bin/php-cs-fixer --diff --dry-run -v fix tests
    - vendor/bin/phpunit